apiVersion: apps/v1
kind: Deployment
metadata:
  name: awk-deployment
  labels:
    app: awk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: awk
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: awk
    spec:
      containers:
      - name: awk-server
        image: awk-server
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5